### ISSUE TITLE
Delta-update fails with capitalized filenames on case-sensitive filesystems

### ISSUE THREAD

**Issue by chroem-** [alexkasko/delta-updater#1]
Hi there.

All filenames seem to be converted to lowercase during the creation of the patch file, so when you go to apply the patch, the library will fail to find the file that is to be patched if it contains un uppercase character.  In my case, this means that if I have a file named "_F_ortress.dat," that gets converted to "_f_ortress.dat" in the patch file, causing the patcher to be unable to find the file to update.

Here's a stack trace:

```
java.io.FileNotFoundException: snapshot_testing/world/data/fortress.dat
    at com.alexkasko.delta.DirDeltaPatcher.check(DirDeltaPatcher.java:99)
    at com.alexkasko.delta.DirDeltaPatcher.patch(DirDeltaPatcher.java:77)
    at com.alexkasko.delta.DirDeltaPatcher.patch(DirDeltaPatcher.java:62)
```

**Comment by alexkasko** [comment]
Hi,

Are you using Mac OS?

I think the problem is here: 
https://github.com/alexkasko/delta-updater/blob/7ece8e975849b968dae14a651a8b1012042c45c3/delta-diff/src/main/java/com/alexkasko/delta/DirDeltaCreator.java#L150

IOCase I use appeared to be broken: 
https://issues.apache.org/jira/browse/IO-171

I added "-c [y/n]" flag to specify case directly in delta-diff 1.1.2 
(binary: 
https://bitbucket.org/alexkasko/share/downloads/delta-diff-1.1.2-distr.tar.gz)

Cannot test it on Mac OS right now though.

On 08/09/2014 07:41 AM, chroem- wrote:

> Hi there.
> 
> All filenames seem to be converted to lowercase during the creation of the patch file, so when you go to apply the patch, the library will fail to find the file that is to be patched if it contains un uppercase character.  In my case, this means that if I have a file named "_F_ortress.dat," that gets converted to "_f_ortress.dat" in the patch file, causing the patcher to be unable to find the file to update.
> 
> Here's a stack trace:
> 
> ```
> java.io.FileNotFoundException: snapshot_testing/world/data/fortress.dat
>   at com.alexkasko.delta.DirDeltaPatcher.check(DirDeltaPatcher.java:99)
>   at com.alexkasko.delta.DirDeltaPatcher.patch(DirDeltaPatcher.java:77)
>   at com.alexkasko.delta.DirDeltaPatcher.patch(DirDeltaPatcher.java:62)
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alexkasko/delta-updater/issues/1

## 

-Alex

**Comment by chroem-** [comment]
Thanks!

The problem was occuring on a server running AWS Linux, which was recieving delta updates from another machine running Windows 7.

I'll test the updated library and report the results as soon as possible.

EDIT: Works great!
